#[START config]
GOOGLE_CLIENT_ID: replaceGoogleClientId
GOOGLE_CLIENT_SECRET: replaceGoogleClientSecret
BOKEH_SECRET: bokehSECRET
BOKEH_URL:  http://example.com
ALLOWED_DOMAIN: @domain.com
APP_SECRET_KEY: replaceAppSecret
#[END config]
